version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfileweb
    ports:
      - "5000:5000"
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    networks:
      - backend

networks: 
  backend:
