version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfileweb
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web

networks: 
  backend:

volumes:
  db-data:
